### PR TITLE
build on node4 and quote versions

### PR DESCRIPTION
**Pull request by stevemao**
0.10 means 0.1 not '0.10'

### CODE REVIEW

**Comment by pksunkara** [comment]
Please use the following for the versions:

```
- '4'
- '3'
- '2'
- '1'
- '0.12'
- '0.10'
- '0.8'
```

**Comment by stevemao** [comment]
Done

**Comment by pksunkara** [comment]
I am sorry to ask you, but can also add this line at the beginning of the file. `sudo: false`. Thanks.

**Comment by stevemao** [comment]
Done

**Comment by pksunkara** [comment]
Thanks :)

**Pull request merged**
